fix doxygen includes
doxygen includes weren't being generated properly (wrong variable
syntax in cmake, multiple doxygen directives that overwrite
eachother, etc). include files are now written correctly, but not
used correctly, as there is no dependency generation currently.
ie: tableio-doxygen depends on icetray-doxygen, but cmake doesn't
know that. this produces errors like

error: Fatal error at line 1 column 1: unexpected end of file
error: Fatal error at line 1 column 1: error while parsing prolog

this is because we're tying to include a doxygen tag file that hasn't
been generated yet (ie: a zero-byte file). it's currently unclear
if multiple doxygen runs (make doxygen && make doxygen) could work
around that.

svn path:/highlander/trunk/; revision:169898